import argparse
parser = argparse.ArgumentParser(description="Automatically Win(dows).")

def parse_args():
    parser.add_argument("ip", help="Target IP address")
    parser.add_argument("protocol", nargs="?", default="", help="Protocol used within NetExec")
    parser.add_argument("-dc", help = "Domain Controler")
    parser.add_argument("-target", "-target_machine", help = "User/Machine we going after")
    parser.add_argument("-user_list", "-user-list", default="", help="Optional user wordlist")
    parser.add_argument("-password_list", "-password-list", default="", help="Optional password list")
    parser.add_argument("-user", "-u", help="Target User")
    parser.add_argument("-password", "-p", help="Target Password")
    parser.add_argument("-hash", "-H", help="Target Hash")
    parser.add_argument("-kerberos", "-k", action="store_true", help="Use Kerberos authentication")
    parser.add_argument("-roast", "-r", action="store_true", help="Run [ASP-Rep/Kerbe]roast attacks")
    parser.add_argument("-extras", "-e", action="store_true", help ="Run all modules including things we never seeing")
    parser.add_argument("-mssql", "-sql", action="store_true", help ="Run MSSQL modules")
    parser.add_argument("-findusers", action="store_true", help = 'Brute force valid users with NMAP')
    parser.add_argument("-enum", action="store_true", help = "Runs enum4Linux to get sysinfo")
    parser.add_argument("-scan", action="store_true", help ="Scans subnet for active machines with NetExec")
    parser.add_argument("-userscan", action="store_true", help = "Gets Users")
    parser.add_argument("-passwd", action="store_true", help="Get Password Policy")
    parser.add_argument("-rpc", action="store_true", help = "Try anonymous rpc and if successful enumerate")
    parser.add_argument("-shares", action="store_true", help="Enumerate SMB Shares")
    parser.add_argument("-getusers", "-get-users", action="store_true", help="Gets all users and outputs to file for easier password spraying")
    parser.add_argument("-ldapsearch", "-ldap", action="store_true", help = "Enumerate users in LDAP")
    parser.add_argument("-bloodhound", action="store_true", help = "Run Bloodhound")
    parser.add_argument("-findDelegation", "-delegation", action="store_true", help="Find Delegations for abuse")
    parser.add_argument("-rbcd", action="store_true", help="Run Resourced Based Constrained Delegation")
    parser.add_argument("-clean", action="store_true", help = "Clean up after RBCD exploit")
    parser.add_argument("-gpoabuse", "-gpo", action="store_true", help="Run GPO Abuse")
    parser.add_argument("-gpoID", help = "ID of the GPO needed for gpoabuse")
    parser.add_argument("-adcs", action="store_true", help="Find vulnerabilities in ADCS and abuse them")
    parser.add_argument("-esc", help="Specify the exact ESC priv esc you want to run")
    parser.add_argument("-skeleton", help="Runs the skeleton key attack with a custom password")
    parser.add_argument("-brute-user", action="store_true", help="Will attempt to brute force valid users")
    parser.add_argument("-dsrm", action="store_true", help="Allow for DA authentication via a stolen DSRM Hash")
    parser.add_argument("-gpoHydra", "-gh", action="store_true", help="Run the GPOHydra persistence mechanism")
    parser.add_argument("-name", "-n", help="GPO name")
    parser.add_argument("-ou", "-o", help="OU path to link GPO")
    parser.add_argument("-action", "-a", help="Action to perform for GPOHydra")
    parser.add_argument("-wallpaper", "-w", help="Change the wallpaper on the target machine")
    parser.add_argument("-party", help="Add 50 privileged, backdoor users")
    return parser.parse_args()